
-- ==========================================================
-- Project : Supermarket Data Engineering Project
-- File    : comprehensive_kpi_queries.sql
-- Purpose : Comprehensive business KPI analysis queries
-- Author  : Rathish
-- ==========================================================


-- ==========================================================
-- Question 33
-- Business Question:
-- What is the total revenue generated by each store?
--
-- Objective:
-- Calculate the total revenue generated by every store
-- to compare overall business performance.
-- ==========================================================

SELECT
    store_id,
    store_name,
    location,
    total_revenue
FROM gold_sales_performance
ORDER BY total_revenue DESC;


-- ==========================================================
-- Question 34
-- Business Question:
-- What is the average transaction value for each store?
--
-- Objective:
-- Measure the average value of customer transactions
-- to understand customer spending behavior.
-- ==========================================================

SELECT
    store_id,
    store_name,
    average_transaction_value
FROM gold_sales_performance
ORDER BY average_transaction_value DESC;

 
-- ==========================================================
-- Question 35
-- Business Question:
-- How many unique products were sold by each store?
--
-- Objective:
-- Measure product diversity across stores.
-- ==========================================================

SELECT
    store_id,
    store_name,
    distinct_products_sold
FROM gold_sales_performance
ORDER BY distinct_products_sold DESC;


-- ==========================================================
-- Question 36
-- Business Question:
-- What is the inventory turnover ratio for each store?
--
-- Objective:
-- Measure how efficiently each store sells its inventory.
-- ==========================================================

SELECT
    store_id,
    ROUND(
        SUM(total_quantity_sold) / SUM(quantity_on_hand),
        2
    ) AS inventory_turnover_ratio
FROM gold_inventory_analysis
GROUP BY store_id
ORDER BY inventory_turnover_ratio DESC;


-- ==========================================================
-- Question 37
-- Business Question:
-- Which are the top 3 product categories based on total sales revenue?
--
-- Objective:
-- Identify the highest-performing product categories to support
-- sales strategy and inventory planning.
-- ==========================================================

SELECT
    category,
    ROUND(SUM(total_revenue), 2) AS total_revenue
FROM gold_product_performance
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 3;


-- ==========================================================
-- Question 38
-- Business Question:
-- What is the market share of each store based on total revenue?
--
-- Objective:
-- Calculate the percentage contribution of each store to the
-- overall revenue generated across all stores.
-- ==========================================================

SELECT
    store_id,
    store_name,
    ROUND(total_revenue, 2) AS total_revenue,
    ROUND(
        (total_revenue / SUM(total_revenue) OVER ()) * 100,
        2
    ) AS market_share_percentage
FROM gold_sales_performance
ORDER BY market_share_percentage DESC;


-- ==========================================================
-- Question 39
-- Business Question:
-- What is the month-on-month sales trend across all stores?
--
-- Objective:
-- Analyze monthly revenue trends to identify seasonal patterns
-- and support business planning.
-- ==========================================================

SELECT
    sales_year,
    sales_month,
    SUM(total_revenue) AS total_revenue
FROM gold_monthly_sales_performance
GROUP BY
    sales_year,
    sales_month
ORDER BY
    sales_year,
    sales_month;